import type { Metadata } from 'next';
import { League_Spartan, Public_Sans } from 'next/font/google';

import './globals.css';

const league_spartan = League_Spartan({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-league-spartan',
  style: ['normal'],
});

const public_sans = Public_Sans({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-public-sans',
  style: ['normal'],
});

export const metadata: Metadata = {
  title: 'Repasando Next js',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es' className={`${league_spartan.variable} ${public_sans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
